services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: livestock-db-test_postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./.env.test
volumes:
  postgres:
