server:
  protocol: "http"
  host: "127.0.0.1"
  port: 5150
  
logger:
  format: full
  level: trace
  directives:
    - axum
    - tower
    - config

db:
  url: {{ get_env( name="TEST_DATABASE_URL", DEFAULT="postgresql://admin:Password@localhost:5433/livestock-db_test") }}
  connection_timeout: 15 # Seconds
  idle_timeout: 5 # Seconds
  max_connections: 1
  min_connections: 1
  auto_migrate: true
  recreate: true

auth:
  access:
    private_key: security/keys/dev/access_key.pem
    public_key: security/keys/dev/access_key_pub.pem
    max_age: 3600 # Seconds One hour
  refresh:
    private_key: security/keys/dev/refresh_key.pem
    public_key: security/keys/dev/refresh_key_pub.pem
    max_age: 604800 # Seconds One week
    
